/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nf.view;

import java.awt.Dimension;
import java.io.File;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import nf.Koneksi;
import nf.alarm.Schedule;
import nf.entity.User;
import nf.implement.ImplUser;
import nf.interfaces.InterUser;

/**
 *
 * @author ACER
 */
public class MenuUtama extends javax.swing.JFrame {
    private User u = new User();
    InterUser daoUser;
    
    public MenuUtama() {
        initComponents();
        daoUser = new ImplUser();
        MenuLogout.setEnabled(false);
        MenuMaster.setVisible(false);
        MenuTransaksi.setVisible(false);
        MenuLaporan.setVisible(false);
        MenuJasa.setVisible(false);
    }

    boolean cekLogin(String user, String pass) {
        boolean hasil = false;
        try {
            u = daoUser.getByUsername(user);
            if (user.equals(u.getUsername()) && pass.equals(u.getPassword())) {
                hasil = true;
            } else {
                hasil = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
        return hasil;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        jDesktopPane1 =  new nf.view.BackgroundPaneDesktop();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuLogin = new javax.swing.JMenuItem();
        MenuLogout = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        MenuMaster = new javax.swing.JMenu();
        MenuSupplier = new javax.swing.JMenuItem();
        MenuKategori = new javax.swing.JMenuItem();
        MenuBarang = new javax.swing.JMenuItem();
        MenuUser = new javax.swing.JMenuItem();
        MenuTransaksi = new javax.swing.JMenu();
        MenuMasuk = new javax.swing.JMenuItem();
        MenuKeluar = new javax.swing.JMenuItem();
        MenuReturnKeluar = new javax.swing.JMenuItem();
        MenuReturnMasuk = new javax.swing.JMenuItem();
        MenuJasa = new javax.swing.JMenu();
        MenuPerawatan = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();
        LaporanBarang = new javax.swing.JMenuItem();
        LaporanSupplier = new javax.swing.JMenuItem();
        BarangMasuk = new javax.swing.JMenuItem();
        BarangKeluar = new javax.swing.JMenuItem();
        LaporanJasa = new javax.swing.JMenuItem();

        jDialog1.setTitle("Login");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Autentifikasi"));

        jLabel4.setText("Username :");

        jLabel2.setText("Password :");

        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });
        TxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test JDesktopPane");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        MenuFile.setText("File");

        MenuLogin.setText("Login");
        MenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginActionPerformed(evt);
            }
        });
        MenuFile.add(MenuLogin);

        MenuLogout.setText("Logout");
        MenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogoutActionPerformed(evt);
            }
        });
        MenuFile.add(MenuLogout);

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuExit);

        jMenuBar1.add(MenuFile);

        MenuMaster.setText("Master");

        MenuSupplier.setText("Supplier");
        MenuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSupplierActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuSupplier);

        MenuKategori.setText("Kategori");
        MenuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKategoriActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuKategori);

        MenuBarang.setText("Barang");
        MenuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuBarang);

        MenuUser.setText("User");
        MenuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuUser);

        jMenuBar1.add(MenuMaster);

        MenuTransaksi.setText("Transaksi");

        MenuMasuk.setText("Barang Masuk");
        MenuMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMasukActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuMasuk);

        MenuKeluar.setText("Barang Keluar");
        MenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKeluarActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuKeluar);

        MenuReturnKeluar.setText("Return Keluar");
        MenuReturnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReturnKeluarActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuReturnKeluar);

        MenuReturnMasuk.setText("Return Masuk");
        MenuReturnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReturnMasukActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuReturnMasuk);

        jMenuBar1.add(MenuTransaksi);

        MenuJasa.setText("Jasa");

        MenuPerawatan.setText("Perawatan");
        MenuPerawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPerawatanActionPerformed(evt);
            }
        });
        MenuJasa.add(MenuPerawatan);

        jMenuBar1.add(MenuJasa);

        MenuLaporan.setText("Laporan");

        LaporanBarang.setText("Barang");
        LaporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanBarangActionPerformed(evt);
            }
        });
        MenuLaporan.add(LaporanBarang);

        LaporanSupplier.setText("Supplier");
        LaporanSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanSupplierActionPerformed(evt);
            }
        });
        MenuLaporan.add(LaporanSupplier);

        BarangMasuk.setText("Barang Masuk");
        BarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangMasukActionPerformed(evt);
            }
        });
        MenuLaporan.add(BarangMasuk);

        BarangKeluar.setText("Barang Keluar");
        BarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangKeluarActionPerformed(evt);
            }
        });
        MenuLaporan.add(BarangKeluar);

        LaporanJasa.setText("Jasa");
        LaporanJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanJasaActionPerformed(evt);
            }
        });
        MenuLaporan.add(LaporanJasa);

        jMenuBar1.add(MenuLaporan);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(610, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserActionPerformed
        // TODO add your handling code here:
        FormUser iUser = new FormUser();
        jDesktopPane1.add(iUser);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iUser.getSize();
        iUser.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iUser.setVisible(true);
    }//GEN-LAST:event_MenuUserActionPerformed

    private void MenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginActionPerformed
        // TODO add your handling code here:
        jDialog1.setSize(375, 190);
        jDialog1.setLocationRelativeTo(null);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_MenuLoginActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        // TODO add your handling code here:
        if (cekLogin(TxtUsername.getText(), TxtPassword.getText())) {
            TxtUsername.setText("");
            TxtPassword.setText("");
            MenuLogin.setEnabled(false);
            MenuLogout.setEnabled(true);
            this.setTitle("Nama " + u.getAkses() + " : " + u.getNama() + "  --  APLIKASI");
            jDialog1.setVisible(false);
            if (u.getAkses().equals("User")) {
                MenuTransaksi.setVisible(true);
                MenuMasuk.setVisible(false);
                MenuKeluar.setVisible(true);
                MenuLaporan.setVisible(false);
                MenuJasa.setVisible(true);
                MenuReturnKeluar.setVisible(false);
                MenuReturnMasuk.setVisible(false);
            } else {
                MenuTransaksi.setVisible(true);
                MenuMaster.setVisible(true);
                MenuLaporan.setVisible(true);
                MenuJasa.setVisible(true);
                MenuMasuk.setVisible(true);
                MenuReturnKeluar.setVisible(true);
                MenuReturnMasuk.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Maaf, Username dan password anda tidak sesuai..!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            TxtUsername.setText("");
            TxtPassword.setText("");
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordActionPerformed

    private void TxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            BtnLoginActionPerformed(null);
        }
    }//GEN-LAST:event_TxtPasswordKeyPressed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jDialog1.setSize(375, 185);
        jDialog1.setLocationRelativeTo(null);
        jDialog1.setVisible(true);
        new Schedule().run();
    }//GEN-LAST:event_formWindowOpened

    private void MenuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSupplierActionPerformed
        // TODO add your handling code here:
        FormSupplier iSupplier = new FormSupplier();
        jDesktopPane1.add(iSupplier);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iSupplier.getSize();
        iSupplier.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iSupplier.setVisible(true);
    }//GEN-LAST:event_MenuSupplierActionPerformed

    private void MenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogoutActionPerformed
        // TODO add your handling code here:
        MenuLogin.setEnabled(true);
        MenuTransaksi.setVisible(false);
        MenuMaster.setVisible(false);
        MenuLogout.setEnabled(false);
        MenuLaporan.setVisible(false);
        MenuJasa.setVisible(false);
        this.setTitle("APLIKASI");
    }//GEN-LAST:event_MenuLogoutActionPerformed

    private void MenuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKategoriActionPerformed
        // TODO add your handling code here:
        FormKategori iKategori = new FormKategori();
        jDesktopPane1.add(iKategori);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iKategori.getSize();
        iKategori.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iKategori.setVisible(true);
    }//GEN-LAST:event_MenuKategoriActionPerformed

    private void MenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangActionPerformed
        // TODO add your handling code here:
        FormBarang iBarang = new FormBarang();
        jDesktopPane1.add(iBarang);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iBarang.getSize();
        iBarang.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iBarang.setVisible(true);
    }//GEN-LAST:event_MenuBarangActionPerformed

    private void MenuMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMasukActionPerformed
        // TODO add your handling code here:
        TransaksiMasuk iMasuk = new TransaksiMasuk();
        jDesktopPane1.add(iMasuk);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iMasuk.getSize();
        iMasuk.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iMasuk.setVisible(true);
    }//GEN-LAST:event_MenuMasukActionPerformed

    private void MenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKeluarActionPerformed
        // TODO add your handling code here:
        TransaksiKeluar iKeluar = new TransaksiKeluar(u.getUsername());
        jDesktopPane1.add(iKeluar);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iKeluar.getSize();
        iKeluar.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iKeluar.setVisible(true);
    }//GEN-LAST:event_MenuKeluarActionPerformed

    private void LaporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanBarangActionPerformed
        // TODO add your handling code here:
        /**
        try {
            File namafile = new File("src/nf/report/repBar.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, Koneksi.dbConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        */
        
        try {
            // TODO add your handling code here:
            File namafile = new File("src/nf/report/repBar.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(namafile.getPath(), null, Koneksi.dbConnection());
            //InputStream is = getClass().getResourceAsStream("/nf/report/repBar.jasper");
            //HashMap has = new HashMap();
            //JasperPrint jasperPrint = JasperFillManager.fillReport(is, has, Koneksi.dbConnection());
            ReportReview rp = new ReportReview(jasperPrint);
            rp.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_LaporanBarangActionPerformed

    private void LaporanSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanSupplierActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/nf/report/repSup.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(namafile.getPath(), null, Koneksi.dbConnection());
            ReportReview rp = new ReportReview(jasperPrint);
            Dimension screenSize = this.getSize();
            Dimension frameSize = rp.getSize();
            rp.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
            rp.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LaporanSupplierActionPerformed

    private void BarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangMasukActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/nf/report/reportMasuk.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(namafile.getPath(), null, Koneksi.dbConnection());
            ReportReview rp = new ReportReview(jasperPrint);
            Dimension screenSize = this.getSize();
            Dimension frameSize = rp.getSize();
            rp.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
            rp.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_BarangMasukActionPerformed

    private void MenuPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPerawatanActionPerformed
        // TODO add your handling code here:
        FormJasa iJasa = new FormJasa();
        jDesktopPane1.add(iJasa);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iJasa.getSize();
        iJasa.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iJasa.setVisible(true);
    }//GEN-LAST:event_MenuPerawatanActionPerformed

    private void BarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangKeluarActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/nf/report/reportKeluar.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(namafile.getPath(), null, Koneksi.dbConnection());
            ReportReview rp = new ReportReview(jasperPrint);
            Dimension screenSize = this.getSize();
            Dimension frameSize = rp.getSize();
            rp.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
            rp.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_BarangKeluarActionPerformed

    private void LaporanJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanJasaActionPerformed
        // TODO add your handling code here:
            try {
            File namafile = new File("src/nf/report/repJasa.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(namafile.getPath(), null, Koneksi.dbConnection());
            ReportReview rp = new ReportReview(jasperPrint);
            Dimension screenSize = this.getSize();
            Dimension frameSize = rp.getSize();
            rp.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
            rp.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LaporanJasaActionPerformed

    private void MenuReturnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReturnKeluarActionPerformed
        // TODO add your handling code here:
        FormReturnKeluar iReturn = new FormReturnKeluar();
        jDesktopPane1.add(iReturn);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iReturn.getSize();
        iReturn.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iReturn.setVisible(true);
    }//GEN-LAST:event_MenuReturnKeluarActionPerformed

    private void MenuReturnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReturnMasukActionPerformed
        // TODO add your handling code here:
        FormReturnMasuk iReturnMasuk = new FormReturnMasuk();
        jDesktopPane1.add(iReturnMasuk);
        Dimension screenSize = this.getSize();
        Dimension frameSize = iReturnMasuk.getSize();
        iReturnMasuk.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        iReturnMasuk.setVisible(true);
    }//GEN-LAST:event_MenuReturnMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BarangKeluar;
    private javax.swing.JMenuItem BarangMasuk;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JMenuItem LaporanBarang;
    private javax.swing.JMenuItem LaporanJasa;
    private javax.swing.JMenuItem LaporanSupplier;
    private javax.swing.JMenuItem MenuBarang;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuJasa;
    private javax.swing.JMenuItem MenuKategori;
    private javax.swing.JMenuItem MenuKeluar;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenuItem MenuLogin;
    private javax.swing.JMenuItem MenuLogout;
    private javax.swing.JMenu MenuMaster;
    private javax.swing.JMenuItem MenuMasuk;
    private javax.swing.JMenuItem MenuPerawatan;
    private javax.swing.JMenuItem MenuReturnKeluar;
    private javax.swing.JMenuItem MenuReturnMasuk;
    private javax.swing.JMenuItem MenuSupplier;
    private javax.swing.JMenu MenuTransaksi;
    private javax.swing.JMenuItem MenuUser;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
